[package]
name = "little-kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[bin]
name="littlekernel"
path="src/kernel.rs"

[build]
target="armv7a-none-eabihf"
target-dir = "build"