[build]
target = "armv7a-none-eabihf"

[target.armv7a-none-eabihf]
runner = "./qemu.sh"
rustflags = [
    "-C", "target-cpu=cortex-a7",
    "-C", "link-arg=--script=.cargo/linker.ld",
    "-C", "link-arg=--no-dynamic-linker",
]


[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]